fix(linting): don't use ref in dependency array in SocialMediaFeedModule
Fix linting error in SocialMediaFeedModule.tsx:
```
Error: Cannot access refs during render

React refs are values that are not needed for rendering. Refs should
only be accessed outside of render, such as in event handlers or
effects. Accessing a ref value (the `current` property) during render
can cause your component not to update as expected
(https://react.dev/reference/react/useRef).

src\core\pageModules\SocialMediaFeedModule\SocialMediaFeedModule.tsx:38:
  36 |       scriptWrapperRef.current.append(documentFragment);
  37 |     }
> 38 |   }, [scriptWrapperRef.current?.innerHTML]);
     |      ^^^^^^^^^^^^^^^^^^^^^^ Cannot access ref value during render
  39 |
  40 |   const sanitizeScripts = (domNode: DOMNode) => {
  41 |     if ('attribs' in domNode) {
(react-hooks/refs)
```

refs HCRC-156